### PR TITLE
Clippy

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 5d46e53 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 5d46e53 with merge 0ebd2bd...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/crc64-rs/builds/129868213)

**Pull request merged**
